---
- name: Configure host
  hosts: localhost
  become: true

  pre_tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true

  tasks:

  roles:
    - role: ../ansible-role-flatpak